$ErrorActionPreference = "Stop"

$src = "C:\Users\Pix-01\Desktop\jang"
$repoRoot = Split-Path -Parent $PSScriptRoot
$backendDest = Join-Path $repoRoot "backend\database\seeders\assets\conflict"
$frontendDest = Join-Path $repoRoot "frontend\public\images\jang"
$manifestTs = Join-Path $repoRoot "frontend\src\data\jang-images.ts"

if (-not (Test-Path -LiteralPath $src)) {
    Write-Error "Source folder not found: $src"
}

New-Item -ItemType Directory -Force -Path $backendDest, $frontendDest | Out-Null

Get-ChildItem -LiteralPath $backendDest -File -ErrorAction SilentlyContinue | Remove-Item -Force
Get-ChildItem -LiteralPath $frontendDest -File -ErrorAction SilentlyContinue | Remove-Item -Force

$files = Get-ChildItem -LiteralPath $src -Filter *.jpg | Sort-Object Name
$paths = New-Object System.Collections.Generic.List[string]
$index = 1

foreach ($file in $files) {
    $name = "jang-{0:D3}.jpg" -f $index
    Copy-Item -LiteralPath $file.FullName -Destination (Join-Path $backendDest $name) -Force
    Copy-Item -LiteralPath $file.FullName -Destination (Join-Path $frontendDest $name) -Force
    $paths.Add("/images/jang/$name")
    $index++
}

$lines = @(
    "// Auto-generated by scripts/sync-jang-images.ps1",
    "export const JANG_IMAGE_PATHS = ["
)

foreach ($path in $paths) {
    $lines += "  `"$path`","
}

$lines += "] as const;"
$lines += ""
$lines += "export const JANG_IMAGE_COUNT = JANG_IMAGE_PATHS.length;"

Set-Content -LiteralPath $manifestTs -Value ($lines -join "`n") -Encoding UTF8

Write-Host "Synced $($paths.Count) images to backend + frontend."
